use_frameworks!

platform :ios, '8.0'

target 'SFTestCode_Example' do
  pod 'SFTestCode', :path => '../'

  target 'SFTestCode_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
